Repository lagom/lagom, pull requests merged in 2018-05, with the labels that each got.

#1332 Update external links
  docs/build.sbt
  docs/manual/common/concepts/ComponentTechnologies.md
  docs/manual/common/guide/logging/SettingsLogger.md
  docs/manual/common/guide/production/ReactivePlatform.md
  docs/manual/java/gettingstarted/IntroGetStarted.md
  docs/manual/java/gettingstarted/JavaPrereqs.md
  docs/manual/java/guide/build/LagomBuild.md
  docs/manual/java/guide/build/MultipleBuilds.md
  docs/manual/java/guide/cluster/Cluster.md
  docs/manual/java/guide/cluster/ReadSideCassandra.md
  docs/manual/java/guide/production/ProductionOverview.md
  docs/manual/java/guide/services/Test.md
  docs/manual/java/releases/Migration13.md
  docs/manual/java/releases/Migration14.md
  docs/manual/scala/gettingstarted/Installation.md
  docs/manual/scala/guide/build/LagomBuild.md
  docs/manual/scala/guide/build/MultipleBuilds.md
  docs/manual/scala/guide/cluster/Cluster.md
  docs/manual/scala/guide/cluster/ReadSideCassandra.md
  docs/manual/scala/guide/production/ProductionOverview.md
  docs/manual/scala/guide/services/ServiceDescriptors.md
  docs/manual/scala/guide/services/ServiceImplementation.md
  docs/manual/scala/releases/Migration14.md
Labels: status:needs-backport, topic:documentation

#1323 Add mention of SlickPersistentComponents. #1105
  docs/manual/scala/guide/cluster/ReadSideSlick.md
  docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/BlogEventProcessor.scala
  docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/SlickBlogApplicationLoader.scala
Labels: status:needs-backport, topic:documentation

#1339 Fix withMessageSerializer API reference
  docs/manual/java/guide/services/MessageSerializers.md
Labels: status:needs-backport, topic:documentation, topic:service-api, type:defect

#1342 Bumping Akka version to 2.5.12
  docs/build.sbt
  project/Dependencies.scala
  service/javadsl/api/src/main/scala/com/lightbend/lagom/internal/javadsl/api/MessageSerializers.scala
Labels: status:needs-backport

#1340 Moving to TestKit since JavaTestKit is deprecated
  dev/maven-plugin/src/maven-test/start-all-2.11/helloworld-impl/src/test/java/sample/helloworld/impl/HelloWorldTest.java
  dev/maven-plugin/src/maven-test/start-all-2.12/helloworld-impl/src/test/java/sample/helloworld/impl/HelloWorldTest.java
  docs/manual/java/guide/cluster/code/docs/home/persistence/Post4Test.java
  docs/manual/java/guide/cluster/code/docs/home/persistence/PostTest.java
  docs/manual/java/guide/cluster/code/docs/home/serialization/EventMigrationTest.java
  docs/src/test/java/docs/home/persistence/CqrsIntegrationTest.java
  jackson/src/test/java/com/lightbend/lagom/serialization/JacksonJsonSerializerTest.java
  pubsub/javadsl/src/test/java/com/lightbend/lagom/javadsl/pubsub/PubSubTest.java
Labels: status:needs-backport, topic:build/tests, topic:documentation, type:improvement

#1350 Fix retries of the Slick offset table creation
  build.sbt
  persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickOffsetStore.scala
  persistence-jdbc/core/src/test/resources/logback-test.xml
  persistence-jdbc/core/src/test/resources/reference.conf
  persistence-jdbc/core/src/test/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickDbTestProvider.scala
  persistence-jdbc/core/src/test/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickOffsetStoreSpec.scala
  persistence-jdbc/scaladsl/src/test/resources/reference.conf
  project/Dependencies.scala
Labels: topic:persistence-api, type:defect

#1347 Stop application resources from being returned twice from getResources
  dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/ClassLoaders.scala
  dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Reloader.scala
Labels: status:needs-backport

#1343 Updated Upgrade description in Migration14.md
  docs/manual/java/releases/Migration14.md
  docs/manual/scala/releases/Migration14.md
Labels: status:needs-backport, topic:documentation

#1354 Final attempt at making CqrsIntegrationTest stable
  docs/build.sbt
  docs/src/test/java/docs/home/persistence/CqrsIntegrationTest.java
Labels: status:needs-backport

#1355 Stop disabling DBModule in tests
  testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala
Labels: status:needs-backport

#1345 Update Scala 2.12 to 2.12.6
  bin/test-2.12
  bin/test-sbt-1.0
  build.sbt
  dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
  dev/sbt-plugin/src/sbt-test/sbt-plugin/cassandra-overrides-default-configs/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/custom-port-range-for-services/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/distribution/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-javadsl/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-scaladsl/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/http-backend-switch/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/injected-configs/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-javadsl/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-scaladsl/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-play-on-conf/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/services-intra-communication/build.sbt
  dev/sbt-scripted-tools/src/main/scala/com/lightbend/lagom/sbt/scripted/ScriptedTools.scala
  docs/build.sbt
  docs/manual/java/guide/build/code/lagom-build.sbt
  docs/manual/java/guide/build/code/multiple-builds.sbt
  docs/manual/java/releases/Migration14.md
  docs/manual/scala/guide/build/code/lagom-build.sbt
  docs/manual/scala/guide/build/code/multiple-builds.sbt
  docs/manual/scala/releases/Migration14.md
  project/Dependencies.scala
  project/Doc.scala
Labels: status:needs-backport, topic:build/tests, type:improvement

#1359 Update sbt-whitesource to 0.1.11
  project/plugins.sbt
Labels: status:needs-backport

#1363 Update documentation for Lightbend Orchestration
  docs/manual/common/concepts/ComponentTechnologies.md
  docs/manual/common/guide/production/code/conductr.sbt
  docs/manual/java/gettingstarted/JavaPrereqs.md
  docs/manual/java/guide/production/ConductR.md
  docs/manual/java/guide/production/ConductRMaven.md
  docs/manual/java/guide/production/ConductRSbt.md
  docs/manual/java/guide/production/ProductionOverview.md
  docs/manual/java/guide/production/index.toc
  docs/manual/scala/guide/cluster/PersistentEntityCassandra.md
  docs/manual/scala/guide/production/ConductR.md
  docs/manual/scala/guide/production/ProductionOverview.md
  docs/manual/scala/guide/production/code/ConductR.scala
  docs/manual/scala/guide/production/index.toc
  docs/manual/scala/guide/services/DependencyInjection.md
  docs/manual/scala/guide/services/ScalaComponents.md
  service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/LagomApplicationLoader.scala
Labels: status:needs-backport

#1364 Update Migration Manager (MiMa) to 0.3.0
  build.sbt
  project/plugins.sbt
Labels: status:needs-backport

#1369 Increase default timeouts for expectations and persisten entity asks
  persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
  persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
Labels: status:needs-backport

#1377 Updates play to 2.6.15
  docs/build.sbt
  project/Dependencies.scala
Labels: topic:core-framework
