Repository lagom/lagom, pull requests merged in 2018-03, with the labels that each got.

#1228 Update Akka to 2.5.11 and Play to 2.6.12
  docs/build.sbt
  project/Dependencies.scala
Labels: status:needs-backport

#1235 Wrong description for MaxMetaspaceSize
  docs/manual/common/guide/build/JVMMemoryOnDev.md
Labels: status:needs-backport, status:needs-forwardport

#1246 Removes docs wrt the metrics service and its endpoints
  docs/manual/java/guide/services/ServiceClients.md
  docs/manual/scala/guide/services/ScalaComponents.md
  docs/manual/scala/guide/services/ServiceClients.md
Labels: status:needs-backport, status:to-review

#1252 Adds UUID PathParamSerializer to list of detauls in javadsl
  service/javadsl/api/src/main/scala/com/lightbend/lagom/internal/javadsl/api/ServiceReader.scala
  service/javadsl/api/src/test/java/com/lightbend/lagom/api/mock/BlogService.java
  service/javadsl/api/src/test/scala/com/lightbend/lagom/internal/api/ServiceReaderSpec.scala
Labels: status:needs-backport

#1247 Fixes default exception deserialization
  service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/deser/ExceptionMessage.java
  service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/TransportErrorCode.java
  service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/TransportException.java
  service/javadsl/api/src/test/scala/com/lightbend/lagom/javadsl/api/transport/TransportExceptionSpec.scala
  service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/deser/ExceptionSerializer.scala
  service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/transport/Exceptions.scala
  service/scaladsl/api/src/test/scala/com/lightbend/lagom/scaladsl/api/ExceptionsSpec.scala
Labels: status:in-progress, status:needs-backport, status:to-review

#1256 Removes wrong prefix in config loading
  service/javadsl/integration-client/src/main/java/com/lightbend/lagom/javadsl/client/integration/LagomClientFactory.java
  service/javadsl/kafka/client/src/main/java/com/lightbend/lagom/javadsl/broker/kafka/KafkaTopicFactory.java
Labels: status:in-progress, status:needs-backport, topic:service-client, type:defect

#1254 Fixes maven plugin types
  dev/maven-plugin/src/main/maven/plugin.xml
Labels: status:in-progress, status:needs-backport

#1257 Adds support for empty Service traits in scala
  service/scaladsl/server/src/main/scala/com/lightbend/lagom/internal/scaladsl/server/ScaladslServerMacroImpl.scala
Labels: topic:core-framework, type:defect

#1258 Remove unnecessary workarounds in ServiceTestSpec
  testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTestSpec.scala
Labels: status:needs-backport

#1264 Increase timeouts for CqrsIntegrationTest
  bin/test-documentation
  docs/src/test/java/docs/home/persistence/CqrsIntegrationTest.java
Labels: status:needs-backport

#1265 Build Maven plugin and support for Scala 2.12 only
  build.sbt
Labels: status:needs-backport

#1261 Update name & link for commercial monitoring product
  docs/manual/common/concepts/ComponentTechnologies.md
Labels: status:needs-backport, status:needs-forwardport, topic:documentation

#1272 Move akka.test.single-expect-default setting
  bin/test-documentation
  docs/build.sbt
Labels: status:needs-backport

#1263 Fix Cassandra and JDBC conflicts in TestKit
  build.sbt
  project/Dependencies.scala
  testkit/core/src/main/scala/com/lightbend/lagom/internal/testkit/CassandraTestServer.scala
  testkit/core/src/main/scala/com/lightbend/lagom/internal/testkit/TestConfig.scala
  testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala
  testkit/javadsl/src/test/scala/com/lightbend/lagom/javadsl/testkit/ServiceTestSpec.scala
  testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTest.scala
  testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTestSpec.scala
Labels: status:needs-backport, status:to-review

#1277 Adds Kafka message timestamps to Metadata
  service/javadsl/kafka/client/src/main/java/com/lightbend/lagom/javadsl/broker/kafka/KafkaMetadataKeys.java
  service/javadsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaSubscriber.scala
  service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
  service/scaladsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/scaladsl/broker/kafka/ScaladslKafkaSubscriber.scala
  service/scaladsl/kafka/client/src/main/scala/com/lightbend/lagom/scaladsl/broker/kafka/KafkaMetadataKeys.scala
  service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala
Labels: status:needs-backport, topic:message-broker-api, type:improvement

#1278 enabled timeout when fetch read-side offset
  persistence-jdbc/core/src/main/resources/reference.conf
  persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickDbProvider.scala
  persistence-jdbc/core/src/test/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickDbTestProvider.scala
  persistence/core/src/main/resources/reference.conf
  persistence/core/src/main/scala/com/lightbend/lagom/internal/persistence/ReadSideConfig.scala
  persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/ReadSideActor.scala
  persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/ReadSideActor.scala
Labels: status:to-review, type:improvement

#1286 Upgrades Slick and akka-persistence-jdbc versions
  docs/manual/java/guide/build/LagomBuild.md
  persistence-jdbc/core/src/main/resources/reference.conf
  project/Dependencies.scala
Labels: status:needs-backport

#1290 Brings ReadSideTestDriver as developed on online-auction
  testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ReadSideTestDriver.java
  testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/ReadSideTestDriver.scala
Labels: topic:persistence-api, topic:testkit
