Repository lagom/lagom, pull requests merged in 2018-07, with the labels that each got.

#1422 Fix Slick tests
  build.sbt
  persistence-cassandra/javadsl/src/test/resources/logback-test.xml
  persistence-cassandra/scaladsl/src/test/resources/logback-test.xml
  persistence-jdbc/core/src/test/resources/logback-test.xml
  persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceSpec.scala
  persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcReadSideSpec.scala
  persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickPersistenceSpec.scala
  persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickPersistentEntityActorSpec.scala
  persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickReadSideSpec.scala
  persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickTestEntityReadSide.scala
  persistence/core/src/test/resources/logback-test.xml
  persistence/scaladsl/src/test/resources/logback-test.xml
Labels: status:needs-backport

#1420 Update deployment information in "core concepts"
  docs/manual/common/concepts/CoreConcepts.md
Labels: status:needs-backport

#1418 Read side actor restart
  persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceSpec.scala
  persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcPersistenceSpec.scala
  persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcReadSideSpec.scala
  persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickPersistenceSpec.scala
  persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/ReadSideActor.scala
  persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/AbstractReadSideSpec.scala
  persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/ReadSideActor.scala
  persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractReadSideSpec.scala
Labels: status:needs-backport

#1421 Remove warnings from docs
  docs/build.sbt
  docs/manual/java/guide/advanced/code/docs/home/actor/WorkerService2Impl.java
  docs/manual/java/guide/advanced/code/docs/home/actor/WorkerServiceImpl.java
  docs/manual/java/guide/services/code/docs/services/MessageSerializers.java
  docs/manual/java/guide/services/code/docs/services/ServiceImplementation.java
  docs/manual/java/guide/services/code/docs/services/test/ServiceTestModule.java
  docs/manual/java/guide/services/code/docs/services/test/StubDependencies.java
  docs/manual/scala/guide/advanced/code/Akka.scala
  docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/CassandraBlogEventProcessor.scala
  docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/PostSpec.scala
  docs/src/test/java/docs/home/persistence/CqrsIntegrationTest.java
  docs/src/test/scala/docs/home/actor/ActorServiceSpec.scala
Labels: status:needs-backport

#1433 Remove unused metrics-service snippet
  docs/manual/scala/guide/services/code/ServiceClients.scala
Labels: status:needs-backport

#1407 Update MultipleBuilds.md
  docs/manual/java/guide/build/MultipleBuilds.md
Labels: topic:documentation

#1442 allow missing application.conf for ServiceClients.
  service/javadsl/integration-client/src/main/java/com/lightbend/lagom/javadsl/client/integration/LagomClientFactory.java
  service/scaladsl/client/src/main/scala/com/lightbend/lagom/scaladsl/client/ServiceClient.scala
Labels: topic:service-client, type:improvement

#1427 Provide Akka Discovery support in dev mode
  build.sbt
  dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/LagomConfig.scala
  dev/service-registry/client-core/src/main/scala/com/lightbend/lagom/internal/registry/AbstractLoggingServiceRegistryClient.scala
  dev/service-registry/client-core/src/main/scala/com/lightbend/lagom/internal/registry/DevModeSimpleServiceDiscovery.scala
  dev/service-registry/client-core/src/main/scala/com/lightbend/lagom/internal/registry/ServiceRegistryClient.scala
  dev/service-registry/client-core/src/test/scala/com/lightbend/lagom/internal/registry/AbstractLoggingServiceRegistryClientSpec.scala
  dev/service-registry/client-core/src/test/scala/com/lightbend/lagom/internal/registry/DevModeSimpleServiceDiscoverySpec.scala
  dev/service-registry/client-javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/registry/JavaServiceRegistryClient.scala
  dev/service-registry/client-javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/registry/ServiceRegistry.java
  dev/service-registry/client-javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/registry/ServiceRegistryModule.scala
  dev/service-registry/client-javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/registry/ServiceRegistryServiceLocator.scala
  dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/registry/ScalaServiceRegistryClient.scala
  dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/registry/ServiceRegistry.scala
  dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/registry/ServiceRegistryServiceLocator.scala
  dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/devmode/LagomDevModeComponents.scala
  project/Dependencies.scala
  service/javadsl/integration-client/src/main/java/com/lightbend/lagom/javadsl/client/integration/LagomClientFactory.java
Labels: topic:grpc

#1470 sbt-sonatype 2.3
  project/plugins.sbt
Labels: topic:core-framework

#1486 Adds some comments on Travis scripts
  bin/test-code-style
Labels: topic:documentation

#1485 Use mimaReportBinaryIssues task instead of custom command
  bin/test-code-style
  build.sbt
Labels: topic:build/tests

#1484 Bind Netty service gateway to the configured host (not 0.0.0.0)
  dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/gateway/NettyServiceGateway.scala
Labels: topic:development-environment

#1476 Remove sbt-site plugin in preparation of sbt 1.x
  project/Protobuf.scala
  project/plugins.sbt
Labels: topic:build/tests

#1483 Extends the usage of CS in Lagom-core (mostly dev mode)
  build.sbt
  dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala
  dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/registry/ServiceRegistration.scala
  dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/devmode/LagomDevModeComponents.scala
  dev/service-registry/registration-javadsl/src/main/scala/com/lightbend/lagom/internal/server/ServiceRegistrationModule.scala
  dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/gateway/AkkaHttpServiceGateway.scala
  dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/gateway/NettyServiceGateway.scala
  dev/service-registry/service-locator/src/test/scala/com/lightbend/lagom/gateway/AkkaHttpServiceGatewaySpec.scala
  service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/LagomApplicationLoader.scala
Labels: topic:core-framework, topic:development-environment

#1493 Adds sbt-sonatype settings after upgrading to version 2.0+
  build.sbt
Labels: topic:build/tests

#1497 Explicitly disables Bintray and sets up Sonatype on dev mode projects
  build.sbt
  docs/manual/java/releases/Migration15.md
  docs/manual/scala/releases/Migration15.md
  project/plugins.sbt
Labels: topic:build/tests
