Repository lagom/lagom, pull requests merged in 2018-10, with the labels that each got.

#1614 Update ReadSideSlick.md
  docs/manual/scala/guide/cluster/ReadSideSlick.md
Labels: status:needs-forwardport, topic:documentation

#1610 Upgrade ssl-config, remove LagomIO, & reconcile SSLContextProvider from Lagom's Dev Mode
  dev/dev-mode-ssl-support/src/main/scala/com/lightbend/lagom/devmode/ssl/LagomDevModeSSLEngineProvider.scala
  dev/dev-mode-ssl-support/src/main/scala/com/lightbend/lagom/devmode/ssl/LagomDevModeSSLHolder.scala
  dev/dev-mode-ssl-support/src/main/scala/com/lightbend/lagom/devmode/ssl/LagomIO.scala
  dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala
  project/Dependencies.scala
  testkit/core/src/main/scala/com/lightbend/lagom/internal/testkit/TestkitSslSetup.scala
  testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala
  testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTest.scala
Labels: review

#1620 Improve readability
  docs/manual/common/guide/devmode/RunningServices.md
Labels: review, status:needs-forwardport

#1623 Fix AggregateEventTag#allTags docs
  persistence/javadsl/src/main/scala/com/lightbend/lagom/javadsl/persistence/AggregateEventTag.scala
  persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/AggregateEventTag.scala
Labels: review, status:needs-backport
