Repository lagom/lagom, pull requests merged in 2018-08, with the labels that each got.

#1498 Adds sbt task to validate `publishTo` settings
  build.sbt
  project/LagomPublish.scala
Labels: topic:build/tests

#1503 Refactor CqrsIntegrationTest
  docs/src/test/java/docs/home/persistence/CqrsIntegrationTest.java
Labels: status:needs-backport

#1502 Adds support for portName on Service Registry (Dev mode)
  build.sbt
  dev/service-registry/client-core/src/main/scala/com/lightbend/lagom/internal/registry/AbstractLoggingServiceRegistryClient.scala
  dev/service-registry/client-core/src/main/scala/com/lightbend/lagom/internal/registry/DevModeSimpleServiceDiscovery.scala
  dev/service-registry/client-core/src/main/scala/com/lightbend/lagom/internal/registry/ServiceRegistryClient.scala
  dev/service-registry/client-core/src/test/scala/com/lightbend/lagom/internal/registry/AbstractLoggingServiceRegistryClientSpec.scala
  dev/service-registry/client-core/src/test/scala/com/lightbend/lagom/internal/registry/DevModeSimpleServiceDiscoverySpec.scala
  dev/service-registry/client-javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/registry/AbstractRegisteredService.java
  dev/service-registry/client-javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/registry/JavaServiceRegistryClient.scala
  dev/service-registry/client-javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/registry/RegisteredService.java
  dev/service-registry/client-javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/registry/ServiceRegistry.java
  dev/service-registry/client-javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/registry/ServiceRegistryService.java
  dev/service-registry/client-javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/registry/ServiceRegistryServiceLocator.scala
  dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/registry/ScalaServiceRegistryClient.scala
  dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/registry/ServiceRegistry.scala
  dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/registry/ServiceRegistryServiceLocator.scala
  dev/service-registry/registration-javadsl/src/main/scala/com/lightbend/lagom/internal/server/ServiceRegistrationModule.scala
  dev/service-registry/service-locator/src/main/java/com/lightbend/lagom/registry/impl/ServiceRegistryImpl.java
  dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/gateway/AkkaHttpServiceGateway.scala
  dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/gateway/NettyServiceGateway.scala
  dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/registry/impl/ServiceLocatorServer.scala
  dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/registry/impl/ServiceRegistryActor.scala
  dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/registry/impl/UnmanagedServices.scala
  dev/service-registry/service-locator/src/test/scala/com/lightbend/lagom/registry/impl/InternalRegistrySpec.scala
  dev/service-registry/service-locator/src/test/scala/com/lightbend/lagom/registry/impl/InternalRouterSpec.scala
  dev/service-registry/service-locator/src/test/scala/com/lightbend/lagom/registry/impl/ServiceRegistryImplSpec.scala
  dev/service-registry/service-locator/src/test/scala/com/lightbend/lagom/registry/impl/ServiceRegistryInteropSpec.scala
  docs/manual/common/guide/devmode/code/build-cassandra-opts.sbt
Labels: topic:development-environment

#1523 Cache entire .sbt directory on Travis builds
  .travis.yml
Labels: status:needs-backport, topic:build/tests

#1519 Minor docs improvement
  docs/manual/common/concepts/ES_CQRS.md
Labels: status:needs-backport, topic:documentation

#1440 Add support for additional Play routers
  docs/manual/java/guide/services/code/docs/services/test/ServiceTestModule.java
  project/Dependencies.scala
  service/javadsl/integration-tests/src/test/java/com/lightbend/lagom/it/none/NoServiceTest.java
  service/javadsl/integration-tests/src/test/java/com/lightbend/lagom/it/routers/AdditionalRoutersService.java
  service/javadsl/integration-tests/src/test/java/com/lightbend/lagom/it/routers/AdditionalRoutersServiceImpl.java
  service/javadsl/integration-tests/src/test/java/com/lightbend/lagom/it/routers/AdditionalRoutersServiceModule.java
  service/javadsl/integration-tests/src/test/java/com/lightbend/lagom/it/routers/AdditionalRoutersServiceTest.java
  service/javadsl/integration-tests/src/test/scala/com/lightbend/lagom/it/ServiceSupport.scala
  service/javadsl/integration-tests/src/test/scala/com/lightbend/lagom/it/routers/TestRouters.scala
  service/javadsl/server/src/main/java/com/lightbend/lagom/javadsl/server/AdditionalRouter.scala
  service/javadsl/server/src/main/java/com/lightbend/lagom/javadsl/server/ServiceGuiceSupport.java
  service/javadsl/server/src/main/scala/com/lightbend/lagom/internal/javadsl/server/AdditionalRoutersProvider.scala
  service/javadsl/server/src/main/scala/com/lightbend/lagom/internal/javadsl/server/JavadslServerBuilder.scala
  service/scaladsl/integration-tests/src/test/scala/com/lightbend/lagom/scaladsl/it/routers/AdditionalRoutersService.scala
  service/scaladsl/integration-tests/src/test/scala/com/lightbend/lagom/scaladsl/it/routers/AdditionalRoutersServiceImpl.scala
  service/scaladsl/integration-tests/src/test/scala/com/lightbend/lagom/scaladsl/it/routers/AdditionalRoutersSpec.scala
  service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/LagomServer.scala
  testkit/javadsl/src/main/scala/com/lightbend/lagom/internal/testkit/EmptyAdditionalRoutersModule.scala
  testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala
Labels: topic:grpc, topic:service-api

#1531 reverts Load.reapply change introduced in #1500
  dev/sbt-plugin/src/main/scala-sbt-1.0/com/lightbend/lagom/sbt/DynamicProjectAdder.scala
Labels: type:defect

#1443 Support SSL in Lagom's DevMode
  build.sbt
  dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/PortAssigner.scala
  dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Reloader.scala
  dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Servers.scala
  dev/build-tool-support/src/test/scala/com/lightbend/lagom/dev/PortAssignerSpec.scala
  dev/dev-mode-ssl-support/src/main/scala/com/lightbend/lagom/devmode/ssl/FakeKeyStoreGenerator.scala
  dev/dev-mode-ssl-support/src/main/scala/com/lightbend/lagom/devmode/ssl/LagomDevModeSSLEngineProvider.scala
  dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServerMojos.scala
  dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceManager.scala
  dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceMojos.scala
  dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala
  dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
  dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/run/RunSupport.scala
  dev/sbt-plugin/src/sbt-test/sbt-plugin/custom-port-range-for-services/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/custom-port-range-for-services/test
  dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/registry/ServiceRegistration.scala
  dev/service-registry/play-integration-javadsl/src/main/scala/com/lightbend/lagom/play/LagomPlayModule.scala
  dev/service-registry/registration-javadsl/src/main/scala/com/lightbend/lagom/internal/server/ServiceRegistrationModule.scala
  dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/gateway/AkkaHttpServiceGateway.scala
  dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/gateway/NettyServiceGateway.scala
  dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/registry/impl/ServiceLocatorServer.scala
  dev/service-registry/service-locator/src/test/scala/com/lightbend/lagom/gateway/AkkaHttpServiceGatewaySpec.scala
  project/Dependencies.scala
  project/SbtMavenPlugin.scala
Labels: topic:development-environment, topic:grpc

#1552 Fixed sentence
  docs/manual/common/concepts/BuildConcepts.md
Labels: status:needs-forwardport

#1555 List all ports bound for each service
  dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/ConsoleHelper.scala
  dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Reloader.scala
  dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/LagomKeys.scala
  dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceManager.scala
  dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceMojos.scala
  dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
Labels: topic:development-environment

#1556 Document SSL support in dev mode
  docs/manual/common/guide/devmode/DevEnvironment.md
  docs/manual/java/gettingstarted/GettingStartedMaven.md
  docs/manual/java/gettingstarted/GettingStartedSbt.md
  docs/manual/java/guide/build/MultipleBuilds.md
  docs/manual/java/guide/devmode/ConfiguringServicesInDevelopment.md
  docs/manual/java/guide/devmode/code/configuring-devmode-services.sbt
  docs/manual/scala/gettingstarted/IntroGetStarted.md
  docs/manual/scala/guide/build/MultipleBuilds.md
Labels: topic:development-environment, topic:documentation

#1548 Updates migration notice for upcoming 1.5.0-M3
  docs/manual/java/releases/Migration15.md
  docs/manual/scala/releases/Migration15.md
Labels: topic:documentation

#1564 Updated akka version to 2.5.16
  docs/build.sbt
  project/Dependencies.scala
Labels: status:needs-backport

#1563 Adds a scripted tests asserting HTTPS availability in dev mode
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/project/Build.scala
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/project/plugins.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/src/main/java/api/FooService.java
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/src/main/java/impl/FooServiceImpl.java
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/src/main/java/impl/Module.java
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/src/main/resources/application.conf
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/test
Labels: topic:development-environment
