Repository lagom/lagom, pull requests merged in 2018-04, with the labels that each got.

#1297 Don't force use of H2 in tests
  persistence-cassandra/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala
  project/Dependencies.scala
  testkit/core/src/main/resources/reference.conf
  testkit/core/src/main/scala/com/lightbend/lagom/internal/testkit/TestConfig.scala
  testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTest.scala
Labels: status:needs-backport, topic:persistence-api, topic:testkit

#1301 Details the execution steps when a command arrives
  docs/manual/java/guide/cluster/PersistentEntity.md
  docs/manual/scala/guide/cluster/PersistentEntity.md
Labels: status:needs-backport, topic:documentation, type:improvement

#1298 Adds 1.4.0 on the mima chain of versions under inspection
  build.sbt
Labels: topic:build/tests, type:defect

#1305 Bumps Play 2.6.13 (and related transitive deps)
  project/Dependencies.scala
Labels: status:needs-backport

#1316 Remove redundant code from Kafka specs
  service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
  service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala
Labels: status:needs-backport

#1117 Additional PersistentEntityRegistry, ReadSide
  persistence-cassandra/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/cassandra/CassandraPersistentEntityRegistry.scala
  persistence-cassandra/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/cassandra/CassandraPersistentEntityRegistry.scala
  persistence-jdbc/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/jdbc/JdbcPersistentEntityRegistry.scala
  persistence-jdbc/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/jdbc/JdbcPersistentEntityRegistry.scala
  persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/AbstractPersistentEntityRegistry.scala
  persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/PersistentEntityActor.scala
  persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/ReadSideImpl.scala
  persistence/javadsl/src/test/scala/com/lightbend/lagom/internal/javadsl/persistence/AbstractPersistentEntityRegistrySpec.scala
  persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/AbstractPersistentEntityActorSpec.scala
  persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/AbstractReadSideSpec.scala
  persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/AbstractPersistentEntityRegistry.scala
  persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/PersistentEntityActor.scala
  persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/ReadSideImpl.scala
  persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistenceComponents.scala
  persistence/scaladsl/src/test/scala/com/lightbend/lagom/internal/scaladsl/persistence/AbstractPersistentEntityRegistrySpec.scala
  persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractPersistentEntityActorSpec.scala
  persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractReadSideSpec.scala
  testkit/javadsl/src/test/scala/com/lightbend/lagom/javadsl/testkit/PersistentEntityTestDriverCompatSpec.scala
  testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/PersistentEntityTestDriverCompatSpec.scala
Labels: status:needs-backport

#1325 small typo, stared -> started
  docs/manual/scala/guide/production/ProductionOverview.md
Labels: status:needs-forwardport

#1326 Fix typo
  docs/manual/java/guide/broker/MessageBrokerApi.md
  docs/manual/scala/guide/broker/MessageBrokerApi.md
Labels: status:needs-forwardport

#1327 Fix typo
  docs/manual/java/guide/broker/KafkaClient.md
  docs/manual/scala/guide/broker/KafkaClient.md
Labels: status:needs-forwardport

#1328 Fix typo
  docs/manual/java/guide/broker/MessageBrokerTesting.md
  docs/manual/scala/guide/broker/MessageBrokerTesting.md
Labels: status:needs-forwardport

#1302 Adds javadoc for BehaviorBuilder
  build.sbt
  persistence/javadsl/src/main/scala/com/lightbend/lagom/javadsl/persistence/PersistentEntity.scala
Labels: status:needs-backport, topic:documentation, topic:persistence-api, type:improvement
