Repository lagom/lagom, pull requests merged in 2018-09, with the labels that each got.

#1567 Fix slow getLocalHost warning message
  dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala
Labels: status:needs-backport

#1475 handle no body as a valid input
  jackson/src/main/java/com/lightbend/lagom/javadsl/jackson/JacksonSerializerFactory.java
  jackson/src/test/java/com/lightbend/lagom/serialization/JacksonSerializerFactoryTest.java
  service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/deser/MessageSerializer.scala
  service/scaladsl/api/src/test/scala/com/lightbend/lagom/scaladsl/api/deser/MessageSerializerSpec.scala
Labels: topic:service-api

#1573 Make SSL opt-in
  build.sbt
  dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/PortAssigner.scala
  dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Reloader.scala
  dev/build-tool-support/src/test/scala/com/lightbend/lagom/dev/PortAssignerSpec.scala
  dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceManager.scala
  dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceMojos.scala
  dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala
  dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
  dev/sbt-plugin/src/sbt-test/sbt-plugin/custom-port-range-for-services/test
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/test
  dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/registry/ServiceRegistration.scala
  dev/service-registry/play-integration-javadsl/src/main/scala/com/lightbend/lagom/play/LagomPlayModule.scala
  dev/service-registry/registration-javadsl/src/main/scala/com/lightbend/lagom/internal/server/ServiceRegistrationModule.scala
Labels: topic:development-environment

#1578 Note TestUtil deprecation in 1.5 migration
  docs/manual/java/releases/Migration15.md
  docs/manual/scala/releases/Migration15.md
Labels: topic:documentation

#1587 Allow multi-mbeans per JVM in Dev Mode
  dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala
Labels: topic:core-framework

#1560 Extends LagomClientFactory to use external ActorSystem
  dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomImport.scala
  docs/manual/java/guide/advanced/IntegratingNonLagom.md
  docs/manual/java/guide/advanced/code/docs/advanced/IntegratingNonLagom.java
  docs/manual/scala/guide/advanced/IntegratingNonLagom.md
  docs/manual/scala/guide/advanced/code/IntegratingNonLagom.scala
  project/Dependencies.scala
  service/javadsl/integration-client/src/main/java/com/lightbend/lagom/javadsl/client/integration/LagomClientFactory.java
  service/javadsl/integration-client/src/test/scala/com/lightbend/lagom/javadsl/client/integration/LagomClientFactorySpec.scala
  service/scaladsl/client/src/main/scala/com/lightbend/lagom/scaladsl/client/ServiceClient.scala
Labels: status:needs-backport

#1599 Adds SSL support for lagom's testkit
  build.sbt
  dev/dev-mode-ssl-support/src/main/scala/com/lightbend/lagom/devmode/ssl/LagomDevModeSSLEngineProvider.scala
  dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala
  testkit/core/src/main/scala/com/lightbend/lagom/internal/testkit/TestkitSslSetup.scala
  testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala
  testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTest.scala
Labels: review, topic:testkit
