Repository lagom/lagom, pull requests merged in 2019-11, with the labels that each got.

#2382 Remove unnecessary `maven-enforcer-plugin` from maven archetype
  build.sbt
  dev/archetypes/maven-java/src/main/resources/archetype-resources/pom.xml
  docs/manual/java/gettingstarted/GettingStartedMaven.md
Labels: status:needs-backport

#2426 DB (Slick/JPA) shutdown must happen after cluster is shut down
  build.sbt
  persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickDbProvider.scala
  persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickProvider.scala
  persistence-jdbc/core/src/test/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickDbTestProvider.scala
  persistence-jdbc/core/src/test/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickOffsetStoreSpec.scala
  persistence-jdbc/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/jdbc/SlickProvider.scala
  persistence-jdbc/javadsl/src/main/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceModule.scala
  persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceSpec.scala
  persistence-jdbc/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcPersistenceComponents.scala
  persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcPersistenceSpec.scala
  persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickPersistenceSpec.scala
  persistence-jpa/javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/persistence/jpa/JpaSessionImpl.java
  persistence-jpa/javadsl/src/test/scala/com/lightbend/lagom/internal/javadsl/persistence/jpa/JpaPersistenceSpec.scala
  persistence/core/src/test/scala/com/lightbend/lagom/persistence/ActorSystemSpec.scala
Labels: type:defect

#2433 Prevent using TLS 1.3 to avoid issues on Java 11.
  .jvmopts
Labels: status:needs-backport-1.5

#2437 Adds explicit deps to use snapshot artifacts on nightly jobs
  project/Dependencies.scala
Labels: status:needs-backport-1.5

#2446 Fix datastax urls
  docs/manual/java/guide/cluster/ReadSideCassandra.md
  docs/manual/scala/guide/cluster/ReadSideCassandra.md
Labels: status:needs-backport-1.5

#2451 Switch to new Slick domain
  docs/manual/java/guide/cluster/PersistentEntityRDBMS.md
  docs/manual/scala/guide/cluster/PersistentEntityRDBMS.md
  docs/manual/scala/guide/cluster/ReadSideRDBMS.md
  docs/manual/scala/guide/cluster/ReadSideSlick.md
Labels: status:needs-backport-1.4, status:needs-backport-1.5

#2457 Migration guide fixes for Scala API
  dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-akka-persistence-typed/src/main/scala/com/example/shoppingcart/impl/ShoppingCartEntity.scala
  dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-akka-persistence-typed/src/main/scala/com/example/shoppingcart/impl/ShoppingCartLoader.scala
  dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-akka-persistence-typed/src/main/scala/com/example/shoppingcart/impl/ShoppingCartServiceImpl.scala
  dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-api/src/main/scala/com/example/shoppingcart/api/ShoppingCartService.scala
  dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-lagom-persistence/src/main/scala/com/example/shoppingcart/impl/ShoppingCartEntity.scala
  dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-lagom-persistence/src/main/scala/com/example/shoppingcart/impl/ShoppingCartServiceImpl.scala
  docs/manual/scala/guide/cluster/MigratingToAkkaPersistenceTyped.md
Labels: status:block-merge

#2460 Fix CassandraClusteredPersistentEntitySpec
  persistence-cassandra/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala
  persistence-cassandra/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala
  persistence/core/src/test/scala/com/lightbend/lagom/persistence/TolerateFailuresWhenRunningContinuousIntegration.scala
  persistence/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
  persistence/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
Labels: status:needs-backport-1.4, status:needs-backport-1.5

#2461 Prefer using events as play-JSON samples
  docs/manual/java/guide/cluster/Serialization.md
  docs/manual/scala/guide/cluster/SerializationPlayJson.md
  docs/manual/scala/guide/cluster/code/docs/home/scaladsl/serialization/AddOrder.scala
  docs/manual/scala/guide/cluster/code/docs/home/scaladsl/serialization/AddPost.scala
  docs/manual/scala/guide/cluster/code/docs/home/scaladsl/serialization/ItemAdded.scala
  docs/manual/scala/guide/cluster/code/docs/home/scaladsl/serialization/OrderAdded.scala
  docs/manual/scala/guide/cluster/code/docs/home/scaladsl/serialization/Registry.scala
  docs/manual/scala/guide/cluster/code/docs/home/scaladsl/serialization/RegistryWithCompression.scala
Labels: topic:documentation

#2485 C*ClusteredPESpec: Don't keyspace-autocreate
  persistence-cassandra/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala
  persistence-cassandra/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala
  persistence/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
  persistence/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
  persistence/testkit/src/main/scala/com/lightbend/lagom/internal/persistence/testkit/AwaitPersistenceInit.scala
Labels: status:needs-backport-1.4, status:needs-backport-1.5

#2495 Add notice about jdbc plugin tagging limitation
  docs/manual/java/guide/cluster/ReadSide.md
  docs/manual/java/guide/cluster/UsingAkkaPersistenceTyped.md
  docs/manual/java/guide/cluster/code/docs/home/persistence/BlogEvent.java
  docs/manual/scala/guide/cluster/ReadSide.md
  docs/manual/scala/guide/cluster/UsingAkkaPersistenceTyped.md
  docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/BlogEvent.scala
  docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/ShardedBlogEventTag.scala
  docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/ShoppingCart.scala
Labels: status:needs-backport-1.4, status:needs-backport-1.5
