Repository lagom/lagom, pull requests merged in 2019-08, with the labels that each got.

#2147 Update to Scala 2.12.9
  .travis.yml
  bin/test-sbt-1.0
  build.sbt
  dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
  dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/cassandra-overrides-default-configs/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/custom-port-range-for-services/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/distribution/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-javadsl/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-scaladsl/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/http-backend-switch/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/injected-configs/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-javadsl/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-scaladsl/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-play-on-conf/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/service-discovery/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/services-intra-communication/build.sbt
  dev/sbt-scripted-tools/src/main/scala/com/lightbend/lagom/sbt/scripted/ScriptedTools.scala
  docs/build.sbt
  docs/manual/java/guide/build/code/lagom-build.sbt
  docs/manual/java/guide/build/code/multiple-builds.sbt
  docs/manual/java/releases/Migration14.md
  docs/manual/scala/guide/build/code/lagom-build.sbt
  docs/manual/scala/guide/build/code/multiple-builds.sbt
  docs/manual/scala/releases/Migration14.md
  project/Dependencies.scala
Labels: status:block-merge, status:needs-backport, status:needs-backport-1.4

#2161 Replace DynamicProjectAdder with sbt.AutoPlugin's extraProjects
  dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
  dev/sbt-plugin/src/sbt-test/sbt-plugin/cross-build/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/cross-build/project/plugins.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/cross-build/test
  dev/sbt-plugin/src/sbt-test/sbt-plugin/distribution/test
Labels: status:needs-backport, status:needs-backport-1.4

#2184 Correctly run tests for sbt 0.13
  .travis.yml
  bin/scriptLib
  bin/test-sbt
  bin/test-sbt-0.13
  dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/project/build.properties
Labels: topic:build/tests

#2189 Isolate multi-jvm job for jdk11
  .circleci/config.yml
Labels: topic:build/tests

#2190 Correct publish settings for dev-env aggregator
  build.sbt
Labels: topic:build/tests

#2194 Sbt 1.2.8 is now required (1.1.0 won't load)
  docs/manual/java/releases/Migration16.md
  docs/manual/scala/releases/Migration16.md
Labels: topic:documentation

#2193 Removes (invalid) overwrite
  persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistenceComponents.scala
Labels: topic:persistence-api, type:defect

#2199 Fix circleCI jabba jdk11 resolution
  .circleci/config.yml
Labels: topic:build/tests

#2211 Align ReadSideTestDriver Java implementation with scaladsl (non-blocking)
  testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ReadSideTestDriver.java
Labels: status:needs-backport
