Repository lagom/lagom, pull requests merged in 2019-07, with the labels that each got.

#2024 Notify build status by email
  .travis.yml
Labels: status:needs-backport, status:needs-backport-1.4

#2030 Fix validateDependencies failure in cron
  bin/test-code-style
Labels: status:needs-backport, status:needs-backport-1.4

#1454 Support Scala 2.13
  .travis.yml
  build.sbt
  project/Dependencies.scala
  project/plugins.sbt
  service/javadsl/kafka/server/src/main/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslRegisterTopicProducers.scala
  service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
  service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala
Labels: topic:build/tests

#2082 .travis.yml: secure email, so forks don't send emails
  .travis.yml
Labels: status:needs-backport, status:needs-backport-1.4

#2111 Fix typo in multiple builds documentation
  docs/manual/java/guide/build/MultipleBuilds.md
Labels: status:needs-backport-1.4, status:needs-forwardport

#2055 Introduces stop/start on ProjectionRegistry
  cluster/core/src/multi-jvm/scala/com/lightbend/lagom/internal/cluster/MultiNodeExpect.scala
  persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcReadSideSpec.scala
  persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/ReadSideActor.scala
  persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/ReadSideImpl.scala
  persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/AbstractReadSideSpec.scala
  persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/ReadSideActor.scala
  persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/ReadSideImpl.scala
  persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractReadSideSpec.scala
  project/Doc.scala
  projection/core/src/main/scala/com/lightbend/lagom/internal/projection/ProjectionRegistry.scala
  projection/core/src/main/scala/com/lightbend/lagom/internal/projection/ProjectionRegistryActor.scala
  projection/core/src/main/scala/com/lightbend/lagom/internal/projection/WorkerHolderActor.scala
  projection/core/src/main/scala/com/lightbend/lagom/projection/State.scala
  projection/core/src/multi-jvm/scala/com/lightbend/lagom/internal/projection/ProjectionRegistrySpec.scala
  projection/core/src/test/scala/com/lightbend/lagom/internal/cluster/projections/ProjectionStateSpec.scala
  projection/javadsl/src/main/java/com/lightbend/lagom/javadsl/projection/Projection.java
  projection/javadsl/src/main/java/com/lightbend/lagom/javadsl/projection/ProjectionWorker.java
  projection/javadsl/src/main/java/com/lightbend/lagom/javadsl/projection/Projections.java
  projection/javadsl/src/main/java/com/lightbend/lagom/javadsl/projection/State.java
  projection/javadsl/src/main/scala/com/lightbend/lagom/javadsl/projection/ProjectionRegistryModule.scala
  projection/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/projection/Projections.scala
  service/core/kafka/server/src/main/scala/com/lightbend/lagom/internal/broker/kafka/Producer.scala
  service/core/kafka/server/src/main/scala/com/lightbend/lagom/internal/broker/kafka/TopicProducerActor.scala
Labels: topic:core-framework, topic:message-broker-api, topic:persistence-api

#2110 Update & properly setup MiMa 0.5.0
  build.sbt
  project/plugins.sbt
Labels: status:needs-backport, status:needs-backport-1.4
