Repository lagom/lagom, pull requests merged in 2019-12, with the labels that each got.

#2491 Fix lookup of external https services
  dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/registry/impl/ServiceRegistryActor.scala
  dev/service-registry/service-locator/src/test/scala/com/lightbend/lagom/registry/impl/ServiceRegistryImplSpec.scala
Labels: status:needs-backport-1.5

#2505 Don't run validateDependencies (whitelist) in CI
  bin/test-code-style
Labels: status:needs-backport-1.4, status:needs-backport-1.5

#2509 Avoid TLS 1.3 when invoking Maven
  build.sbt
Labels: status:needs-backport-1.5

#2514 Fix an MSDN link
  docs/manual/common/concepts/ESAdvantage.md
Labels: status:needs-backport-1.4, status:needs-backport-1.5

#2520 Realise the Oracle DB URL 301
  docs/manual/common/guide/cluster/ChoosingADatabase.md
  docs/manual/java/guide/cluster/PersistentEntityRDBMS.md
  docs/manual/scala/guide/cluster/PersistentEntityRDBMS.md
Labels: status:needs-backport-1.4, status:needs-backport-1.5

#2512 Update sbt plugins
  build.sbt
  docs/project/plugins.sbt
  project/plugins.sbt
Labels: status:block-merge

#2563 Datastax URLs are archived again..
  docs/manual/java/guide/cluster/ReadSideCassandra.md
Labels: status:needs-backport-1.5

#2568 Datastax URLs are archived again.. (Scala)
  docs/manual/scala/guide/cluster/ReadSideCassandra.md
Labels: status:needs-backport-1.5

#2572 Tweak Akka snapshot handling
  build.sbt
  dev/sbt-scripted-tools/src/main/scala/com/lightbend/lagom/sbt/scripted/ScriptedTools.scala
  project/AkkaSnapshotRepositories.scala
Labels: status:needs-backport-1.5
