Repository lagom/lagom, pull requests merged in 2019-03, with the labels that each got.

#1766 Adds mention to release notes wrt other version bumps
  docs/manual/java/releases/Migration15.md
  docs/manual/scala/releases/Migration15.md
Labels: status:needs-backport

#1767 Adds instructions to bump from lagom 1.4.latest only
  docs/manual/java/releases/Migration15.md
  docs/manual/scala/releases/Migration15.md
Labels: status:in-progress, status:needs-backport

#1765 Migration from LBO to manual deployment
  docs/manual/java/releases/Migration15.md
  docs/manual/scala/releases/Migration15.md
Labels: status:needs-backport

#1769 First removal of LBO in ref pages
  docs/manual/scala/guide/advanced/IntegratingNonLagom.md
  docs/manual/scala/guide/services/DependencyInjection.md
  docs/manual/scala/guide/services/ScalaComponents.md
Labels: status:needs-backport

#1774 Edit production overview
  docs/manual/java/guide/production/ProductionOverview.md
  docs/manual/scala/guide/production/ProductionOverview.md
Labels: status:needs-backport

#1762 Update to Alpakka Kafka 1.0
  project/Dependencies.scala
Labels: status:in-progress

#1776 Renamed LB Reactive Platform to LB Platform in docs
  cluster/core/src/main/resources/play/reference-overrides.conf
  docs/manual/common/guide/production/EnterpriseSuite.md
Labels: status:needs-backport

#1778 Bumps maven-core to bump transitive deps
  docs/manual/java/gettingstarted/JavaPrereqs.md
  docs/manual/java/releases/Migration15.md
  project/Dependencies.scala
Labels: status:in-progress, status:needs-backport

#1779 Move new features to Highlight. Add additionalRouters and gRPC
  docs/manual/common/releases/Highlights15.md
  docs/manual/java/releases/Highlights15.md
  docs/manual/java/releases/Migration15.md
  docs/manual/scala/releases/Highlights15.md
  docs/manual/scala/releases/Migration15.md
Labels: status:needs-backport

#1785 References new Kubernetes / OpenShift deployment guide
  docs/manual/java/releases/Migration15.md
  docs/manual/scala/releases/Migration15.md
Labels: status:needs-backport

#1789 Force dependency to evict guava 16.0.1
  project/Dependencies.scala
Labels: status:needs-backport

#1784 added a missing space character
  docs/manual/java/guide/devmode/ServiceLocator.md
Labels: status:needs-backport

#1794 Update to sbt-whitesource v0.1.14
  project/plugins.sbt
Labels: status:needs-backport

#1795 Bumps akka management
  project/Dependencies.scala
Labels: status:in-progress, status:needs-backport

#1799 Update Travis CI badge
  README.md
Labels: status:needs-backport

#1790 Update sbt-unidoc to version 0.4.2
  project/Doc.scala
  project/plugins.sbt
Labels: status:in-progress

#1803 Initial fixes for Java 11
  .travis.yml
  bin/test-sbt-1.0
  docs/manual/java/releases/Highlights15.md
  docs/manual/scala/releases/Highlights15.md
  project/Dependencies.scala
  service/javadsl/api/src/main/scala/com/lightbend/lagom/internal/javadsl/api/ServiceReader.scala
Labels: status:needs-backport

#1815 minor fix in docs and import cleanup
  docs/manual/java/guide/cluster/PersistentEntity.md
  docs/manual/scala/guide/cluster/PersistentEntity.md
  persistence-cassandra/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraReadSide.scala
  persistence/core/src/main/scala/com/lightbend/lagom/internal/persistence/ReadSideConfig.scala
Labels: status:needs-backport, status:needs-forwardport, topic:documentation

#1814 Adds a checklist of sorts to ProductionOverview
  docs/manual/java/guide/production/ProductionOverview.md
  docs/manual/scala/guide/production/ProductionOverview.md
Labels: status:needs-backport

#1816 Removed ConductR goal from maven plugin
  dev/maven-plugin/src/main/maven/plugin.xml
  dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/RenameConductRBundleMojo.scala
Labels: status:needs-backport

#1817 Bump Akka HTTP 10.1.8
  project/Dependencies.scala
Labels: status:needs-backport

#1792 Update Lightbend product references
  docs/manual/common/concepts/ComponentTechnologies.md
  docs/manual/common/concepts/ScalableDeployment.md
  docs/manual/common/guide/production/EnterpriseSuite.md
  docs/manual/common/guide/production/LightbendPlatform.md
  docs/manual/java/guide/cluster/Cluster.md
  docs/manual/java/guide/production/index.toc
  docs/manual/scala/guide/cluster/Cluster.md
  docs/manual/scala/guide/production/index.toc
Labels: status:needs-backport

#1818 Document new defaults in clustering formation settings
  cluster/core/src/main/resources/reference.conf
  docs/manual/java/releases/Migration15.md
  docs/manual/scala/releases/Migration15.md
Labels: status:needs-backport

#1821 Added service locator dependency info
  docs/manual/java/releases/Migration15.md
  docs/manual/scala/releases/Migration15.md
Labels: status:needs-backport

#1823 Only run versionSyncCheck if NOT a cron job
  bin/test-code-style
Labels: status:needs-backport

#1834 Prefer using the actual Location
  docs/manual/common/guide/production/LightbendPlatform.md
Labels: status:needs-forwardport

#1835 Update to latest AdoptOpenJDK versions
  .travis.yml
Labels: status:needs-backport, status:needs-backport-1.4
