Repository lagom/lagom, pull requests merged in 2019-02, with the labels that each got.

#1723 Upgrade Slick and Akka Persistence JDBC
  project/Dependencies.scala
Labels: status:needs-backport

#1729 Updates JSON snippet in service API
  docs/manual/common/guide/devmode/DevEnvironment.md
Labels: status:needs-backport

#1725 Adds support for Akka Cluster Bootstrap
  cluster/core/src/main/resources/reference.conf
  cluster/core/src/main/scala/com/lightbend/lagom/internal/cluster/JoinClusterImpl.scala
  dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/LagomConfig.scala
  docs/manual/java/guide/cluster/Cluster.md
  docs/manual/scala/guide/cluster/Cluster.md
  docs/src/test/scala/com/lightbend/lagom/docs/ServiceSupport.scala
  persistence-cassandra/javadsl/src/test/java/com/lightbend/lagom/javadsl/persistence/PersistentEntityRefTest.java
  persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/PersistentEntityRefSpec.scala
  persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceModuleSpec.scala
  persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
  persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
  persistence/testkit/src/main/scala/com/lightbend/lagom/internal/persistence/testkit/PersistenceTestConfig.scala
  project/Dependencies.scala
  service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
  testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/ProducerStubSpec.scala
  testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/TopicPublishingSpec.scala
Labels: in progress, status:needs-backport

#1740 Don't fail whitelist validation in cron
  project/Dependencies.scala
Labels: in progress

#1741 Merges travis stages
  .travis.yml
Labels: in progress, status:needs-backport

#1737 Bumps Akka version to 2.5.21
  docs/build.sbt
  persistence-jdbc/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/jdbc/JdbcReadSideImpl.scala
  project/Dependencies.scala
  pubsub/javadsl/src/main/scala/com/lightbend/lagom/javadsl/pubsub/PubSubRef.scala
  service/javadsl/integration-tests/src/test/scala/com/lightbend/lagom/it/JavadslErrorHandlingSpec.scala
  service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
Labels: in progress, status:needs-backport

#1742 Adds unit tests for SSL testkit API
  testkit/javadsl/src/test/java/com/lightbend/lagom/javadsl/testkit/TestOverTlsTest.java
  testkit/javadsl/src/test/java/com/lightbend/lagom/javadsl/testkit/services/tls/TestTlsService.java
  testkit/javadsl/src/test/scala/com/lightbend/lagom/javadsl/testkit/TestOverTlsSpec.scala
  testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/TestOverTlsSpec.scala
Labels: status:needs-backport

#1746 Honour HeaderFilters
  service/core/client/src/main/scala/com/lightbend/lagom/internal/client/ClientServiceCallInvoker.scala
Labels: status:in-progress, status:needs-backport

#1738 Adds health-check and extended documentation on Akka Cluster Bootstrap
  akka-management/core/src/main/resources/reference.conf
  akka-management/core/src/main/scala/com/lightbend/lagom/internal/akka/management/AkkaManagementTrigger.scala
  akka-management/javadsl/src/main/resources/reference.conf
  akka-management/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/server/AkkaManagementModule.scala
  akka-management/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/server/AkkaManagementComponents.scala
  build.sbt
  cluster/core/src/main/resources/reference.conf
  cluster/core/src/main/scala/com/lightbend/lagom/internal/cluster/JoinClusterImpl.scala
  cluster/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/cluster/JoinCluster.scala
  cluster/javadsl/src/main/scala/com/lightbend/lagom/javadsl/cluster/testkit/ActorSystemModule.scala
  cluster/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/cluster/ClusterComponents.scala
  docs/manual/java/guide/cluster/Cluster.md
  docs/manual/java/releases/Migration15.md
  docs/manual/scala/guide/cluster/Cluster.md
  docs/manual/scala/releases/Migration15.md
  persistence-cassandra/javadsl/src/test/java/com/lightbend/lagom/javadsl/persistence/PersistentEntityRefTest.java
  persistence-cassandra/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala
  persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/PersistentEntityRefSpec.scala
  persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceModuleSpec.scala
  persistence-jdbc/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcClusteredPersistentEntitySpec.scala
  persistence-jdbc/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickClusteredPersistentEntitySpec.scala
  persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
  persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
  persistence/testkit/src/main/scala/com/lightbend/lagom/internal/persistence/testkit/PersistenceTestConfig.scala
  project/Dependencies.scala
  service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
  service/javadsl/server/src/main/resources/reference.conf
  service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala
  service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/LagomApplicationLoader.scala
  testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala
Labels: status:needs-backport

#1755 Update Akka Manangement to 1.0.0-RC3
  akka-management/core/src/main/resources/reference.conf
  docs/manual/java/guide/cluster/Cluster.md
  docs/manual/scala/guide/cluster/Cluster.md
  project/Dependencies.scala
Labels: status:needs-backport

#1607 Adds SSL docs for devmode and tests
  dev/maven-plugin/src/main/maven/plugin.xml
  dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceMojos.scala
  docs/manual/java/guide/devmode/ConfiguringServicesInDevelopment.md
  docs/manual/java/guide/devmode/code/build-service.sbt
  docs/manual/java/guide/services/Test.md
  docs/manual/java/releases/Migration15.md
  docs/manual/scala/guide/devmode/ConfiguringServicesInDevelopment.md
  docs/manual/scala/guide/devmode/code/build-service.sbt
  docs/manual/scala/guide/services/TestingServices.md
  docs/manual/scala/releases/Migration15.md
  testkit/javadsl/src/test/java/com/lightbend/lagom/javadsl/testkit/TestOverTlsTest.java
  testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/TestOverTlsSpec.scala
Labels: status:needs-backport, topic:documentation

#1757 Add logging to AkkaManagementTrigger
  akka-management/core/src/main/scala/com/lightbend/lagom/internal/akka/management/AkkaManagementTrigger.scala
  cluster/core/src/main/scala/com/lightbend/lagom/internal/cluster/JoinClusterImpl.scala
Labels: status:needs-backport

#1758 Enables akka-mngt and removes unnecessary config overrides
  akka-management/core/src/main/resources/reference.conf
  persistence-cassandra/javadsl/src/test/java/com/lightbend/lagom/javadsl/persistence/PersistentEntityRefTest.java
  persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/PersistentEntityRefSpec.scala
  persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceModuleSpec.scala
  persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
  persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
  persistence/testkit/src/main/scala/com/lightbend/lagom/internal/persistence/testkit/PersistenceTestConfig.scala
  service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
  service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala
  testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTest.scala
Labels: status:needs-backport

#1761 Maven archetype cleanup
  dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__Command.java
  dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__Event.java
  dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__ServiceImpl.java
  dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/test/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__EntityTest.java
Labels: status:needs-backport
