Repository lagom/lagom, pull requests merged in 2019-04, with the labels that each got.

#1844 Update reactive-platform --> lightbend-platform
  docs/manual/common/guide/production/LightbendPlatform.md
  docs/manual/java/releases/Highlights15.md
  docs/manual/scala/releases/Highlights15.md
Labels: status:needs-backport, status:needs-backport-1.4

#1848 Update plugin versions
  project/plugins.sbt
Labels: status:needs-backport

#1841 Build only the tags
  .travis.yml
Labels: status:needs-backport

#1842 added some ServiceTest setup clarification when mixing persistence
  docs/manual/java/guide/services/Test.md
  docs/manual/scala/guide/services/TestingServices.md
Labels: status:needs-forwardport

#1866 set MiMa to check against 1.5.0 only
  build.sbt
Labels: status:needs-backport

#1870 Migration guide should refer to Akka 2.5.22
  docs/manual/java/releases/Migration15.md
  docs/manual/scala/releases/Migration15.md
Labels: status:needs-backport

#1864 Adds Couchbase and SQL Server. Lowers C* recommendation
  docs/manual/java/guide/cluster/PersistentEntity.md
  docs/manual/scala/guide/cluster/PersistentEntity.md
Labels: status:needs-backport

#1886 Use the same JVM for sbt locally and in travis
  .jvmopts
  .travis-jvmopts
  bin/scriptLib
Labels: status:needs-backport, status:needs-backport-1.4, topic:build/tests

#1883 Integrates akka discovery service locator in Lagom
  akka-service-locator/core/src/main/resources/reference.conf
  akka-service-locator/core/src/main/scala/com/lightbend/lagom/internal/client/AkkaDiscoveryHelper.scala
  akka-service-locator/core/src/main/scala/com/lightbend/lagom/internal/client/ServiceNameMapper.scala
  akka-service-locator/core/src/test/scala/com/lightbend/lagom/internal/client/ServiceNameMapperSpec.scala
  akka-service-locator/javadsl/src/main/java/com/lightbend/lagom/javadsl/akka/discovery/AkkaDiscoveryServiceLocator.java
  akka-service-locator/javadsl/src/main/java/com/lightbend/lagom/javadsl/akka/discovery/AkkaDiscoveryServiceLocatorModule.java
  akka-service-locator/javadsl/src/main/resources/reference.conf
  akka-service-locator/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/akka/discovery/AkkaDiscoveryComponents.scala
  akka-service-locator/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/akka/discovery/AkkaDiscoveryServiceLocator.scala
  build.sbt
  dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomImport.scala
  docs/build.sbt
  docs/manual/java/guide/production/AkkaDiscoveryIntegration.md
  docs/manual/java/guide/production/ProductionOverview.md
  docs/manual/java/guide/production/code/akka-discovery-dependency.sbt
  docs/manual/java/guide/production/index.toc
  docs/manual/java/releases/Migration15.md
  docs/manual/scala/guide/production/AkkaDiscoveryIntegration.md
  docs/manual/scala/guide/production/ProductionOverview.md
  docs/manual/scala/guide/production/code/AkkaDiscoveryIntegration.scala
  docs/manual/scala/guide/production/code/akka-discovery-dependency.sbt
  docs/manual/scala/guide/production/index.toc
  docs/manual/scala/guide/services/ScalaComponents.md
  docs/manual/scala/releases/Migration15.md
  project/Dependencies.scala
Labels: status:needs-backport
