Repository lagom/lagom, pull requests merged in 2019-01, with the labels that each got.

#1671 Update to Alpakka Kafka 1.0-RC1
  project/Dependencies.scala
Labels: review

#1702 Upgrade to Scala 2.12.8
  bin/test-2.12
  bin/test-sbt-1.0
  dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
  dev/sbt-plugin/src/sbt-test/sbt-plugin/cassandra-overrides-default-configs/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/custom-port-range-for-services/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/distribution/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-javadsl/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-scaladsl/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/http-backend-switch/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/injected-configs/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-javadsl/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-scaladsl/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-play-on-conf/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/run/build.sbt
  dev/sbt-plugin/src/sbt-test/sbt-plugin/services-intra-communication/build.sbt
  dev/sbt-scripted-tools/src/main/scala/com/lightbend/lagom/sbt/scripted/ScriptedTools.scala
  docs/build.sbt
  docs/manual/java/guide/build/code/lagom-build.sbt
  docs/manual/java/guide/build/code/multiple-builds.sbt
  docs/manual/java/releases/Migration14.md
  docs/manual/scala/guide/build/code/lagom-build.sbt
  docs/manual/scala/guide/build/code/multiple-builds.sbt
  docs/manual/scala/releases/Migration14.md
  project/Dependencies.scala
Labels: in progress, status:needs-backport

#1687 Update link to akka-persistence-cassandra's reference.conf
  docs/manual/java/guide/cluster/PersistentEntityCassandra.md
  docs/manual/scala/guide/cluster/PersistentEntityCassandra.md
Labels: status:needs-forwardport

#1711 Build using AdoptOpenJDK 8 & 11
  .travis.yml
Labels: status:needs-backport

#1670 Make use of new Akka Discovery
  dev/service-registry/client-core/src/main/resources/reference.conf
  dev/service-registry/client-core/src/main/scala/com/lightbend/lagom/internal/registry/DevModeServiceDiscovery.scala
  dev/service-registry/client-core/src/test/scala/com/lightbend/lagom/internal/registry/DevModeServiceDiscoverySpec.scala
  dev/service-registry/client-javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/registry/ServiceRegistryModule.scala
  dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/devmode/LagomDevModeComponents.scala
  persistence/javadsl/src/main/java/com/lightbend/lagom/javadsl/persistence/PersistentEntityRef.java
  persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/AbstractPersistentEntityRegistry.scala
  project/Dependencies.scala
Labels: backlog

#1722 Update to Play 2.7.0 and dependencies
  project/Dependencies.scala
Labels: status:needs-backport
