Repository lagom/lagom, pull requests merged in 2019-05, with the labels that each got.

#1890 Upgrades to Play 2.7.2
  docs/build.sbt
  project/Dependencies.scala
Labels: status:needs-backport

#1895 MiMa checks against 1.5.1
  build.sbt
Labels: status:needs-backport

#1908 Update/sbt java formatter 0.4.4
  docs/manual/java/guide/services/code/docs/services/AdditionalRouters.java
  docs/project/plugins.sbt
  project/plugins.sbt
  service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/ServiceInfo.java
  service/javadsl/client/src/main/java/com/lightbend/lagom/javadsl/client/ConfigurationServiceLocator.java
  testkit/javadsl/src/test/java/com/lightbend/lagom/javadsl/testkit/ProducerStubTest.java
Labels: status:needs-backport, status:needs-backport-1.4

#1922 Add protobuf akka serializers
  cluster/core/src/main/resources/reference.conf
Labels: status:needs-backport

#1941 Build cron jobs!!
  .travis.yml
Labels: status:needs-backport, status:needs-backport-1.4

#1909 Use scalafmt plugin
  bin/scalafmt
  bin/test-code-style
  bin/test-documentation
  docs/.scalafmt.conf
  docs/project/plugins.sbt
  project/plugins.sbt
Labels: status:needs-backport

#1953 add CODEOWNERS
  .github/CODEOWNERS
Labels: status:needs-backport

#1940 Setup default discovery methods
  akka-service-locator/core/src/main/resources/reference.conf
  docs/manual/java/guide/production/AkkaDiscoveryIntegration.md
  docs/manual/scala/guide/production/AkkaDiscoveryIntegration.md
Labels: status:needs-backport

#1904 Use Akka 2.6.0-M1
  bin/scriptLib
  dev/reloadable-server/src/main/resources/play/reference-overrides.conf
  docs/build.sbt
  docs/manual/java/releases/Migration15.md
  docs/manual/java/releases/Migration16.md
  docs/manual/java/releases/index.toc
  docs/manual/scala/releases/Migration16.md
  docs/manual/scala/releases/index.toc
  docs/src/test/scala/docs/home/actor/ActorServiceSpec.scala
  persistence/testkit/src/main/scala/com/lightbend/lagom/internal/persistence/testkit/PersistenceTestConfig.scala
  project/Dependencies.scala
  pubsub/javadsl/src/test/java/com/lightbend/lagom/javadsl/pubsub/PubSubTest.java
  pubsub/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/pubsub/PubSubSpec.scala
  service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
  service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala
Labels: topic:build/tests, type:updates, type:upstream
