Repository lagom/lagom, pull requests merged in 2020-11, with the labels that each got.

#3044 Update play-file-watch to 1.1.13
  project/Dependencies.scala
Labels: status:merge-when-green

#3039 Update scala-collection-compat to 2.2.0
  project/Dependencies.scala
Labels: status:merge-when-green

#3086 don't run awaitPersistenceInit for JDBC
  persistence/testkit/src/main/scala/com/lightbend/lagom/internal/persistence/testkit/AwaitPersistenceInit.scala
Labels: status:merge-when-green

#3070 junit 4.13.1 (was 4.13)
  dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomImport.scala
  docs/build.sbt
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#3092 Add `Unauthorized` and `TooManyRequests` codes and exceptions
  service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/TooManyRequests.java
  service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/TransportErrorCode.java
  service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/TransportException.java
  service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/Unauthorized.java
  service/javadsl/api/src/test/scala/com/lightbend/lagom/javadsl/api/transport/TransportExceptionSpec.scala
  service/javadsl/server/src/main/scala/com/lightbend/lagom/internal/javadsl/server/JavadslServerBuilder.scala
  service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/transport/Exceptions.scala
  service/scaladsl/api/src/test/scala/com/lightbend/lagom/scaladsl/api/ExceptionsSpec.scala
Labels: status:merge-when-green, type:improvement

#3090 [1.6.x] Update Play to 2.8.4
  docs/build.sbt
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#3096 sbt-plugin: handle AssertionError from zinc compilation
  dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/run/RunSupport.scala
Labels: status:merge-when-green

#3117 sbt-sonatype 3.9.5 (was 3.9.4)
  project/plugins.sbt
Labels: status:merge-when-green, type:updates

#3113 hibernate-core 5.4.23.Final (was 5.4.22.Final)
  docs/build.sbt
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#3109 byte-buddy 1.10.18 (was 1.10.14)
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#3102 akka-management, ... 1.0.9 (was 1.0.8)
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#3103 typesafe:config 1.4.1 (was 1.4.0)
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#3108 spray-json 1.3.6 (was 1.3.5)
  project/Dependencies.scala
Labels: status:merge-when-green, type:updates

#3121 log command type and entity id on ask exception
  persistence/javadsl/src/main/java/com/lightbend/lagom/javadsl/persistence/PersistentEntityRef.java
  persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistentEntityRef.scala
Labels: status:merge-when-green
