Repository lagom/lagom, pull requests merged in 2021-04, with the labels that each got.

#3210 Maven BOM for Lagom
  build.sbt
  project/plugins.sbt
Labels: status:merge-when-green

#3213 Preparing a Lagom 1.6.5 release
  build.sbt
  dev/sbt-scripted-tools/src/main/scala/com/lightbend/lagom/sbt/scripted/ScriptedTools.scala
  docs/build.sbt
  docs/manual/common/guide/production/LightbendPlatform.md
  docs/manual/java/guide/build/MultipleBuilds.md
  docs/manual/java/guide/build/code/multiple-builds.sbt
  docs/manual/scala/guide/build/MultipleBuilds.md
  docs/manual/scala/guide/build/code/multiple-builds.sbt
  docs/project/plugins.sbt
  project/AkkaSnapshotRepositories.scala
  project/Dependencies.scala
  project/LagomPublish.scala
  project/plugins.sbt
Labels: status:merge-when-green

#3217 [1.6.x] Sync exception logging level between Scala and Java server implementations
  service/scaladsl/server/src/main/scala/com/lightbend/lagom/internal/scaladsl/server/ScaladslServiceRouter.scala
Labels: status:merge-when-green, type:defect

#3233 hibernate-core 5.4.30.Final (was 5.4.28.Final)
  docs/build.sbt
  project/Dependencies.scala
Labels: type:updates

#3229 genjavadoc-plugin 0.17 (was 0.16)
  project/Doc.scala
Labels: type:updates

#3228 ssl-config-core 0.4.3 (was 0.4.2)
  project/Dependencies.scala
Labels: type:updates

#3227 play-file-watch 1.1.16 (was 1.1.14)
  project/Dependencies.scala
Labels: type:updates

#3238 Update scalasteward settings
  .scala-steward.conf
Labels: status:merge-when-green
